services:
  web:
    build: .
    ports:
      - 8000:80
    depends_on:
      - dev_db
  dev_db:

    image: "postgres"
    restart: always

    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tasty_dev_db
    expose:
      - 5432