


services:
  web:
    build: .
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      dev_db:
        condition: service_healthy
      test_db:
        condition: service_healthy


  dev_db:
    image: postgres:14.1-alpine

    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5455:5433'
    volumes:
      - dev_db:/var/lib/postgresql/data
  test_db:
    image: postgres:14.1-alpine

    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5456:5432'
    volumes:
      - test_db:/var/lib/postgresql/data
volumes:
  dev_db:
    driver: local
  test_db:
    driver: local
